name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup
        run: meson setup build/
      - name: Check Format
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy
      - name: Test
        run: cargo test --verbose
